# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 欢迎来到Conke胡的个人博客！
email: conke.hu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <h1>胡思&nbsp;<sub>不乱想</sub></h1>
  <h1>胡言&nbsp;<sub>不乱语</sub></h1>
  <h1>胡作&nbsp;<sub>不非为</sub></h1>
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
  # - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
